### ISSUE TITLE
Error: Cannot convert Intel container!

### ISSUE THREAD

**Issue by AndyLavr** [platomav/MCExtractor#12]
-------[ MC Extractor v1.15.0 r59 ]-------

File (1/1): cpu40671_plat22_ver0000001D_2018-01-21_PRD_A34C93F0.bin

Error: Cannot convert Intel container!

+---------------------------------------------------------------------------------+
|                                      Intel                                      |
+---+-------+-------------+----------+------------+------+--------+--------+------+
| # | CPUID | Platform ID | Revision |    Date    | Type |  Size  | Offset | Last |
+---+-------+-------------+----------+------------+------+--------+--------+------+
| 1 | 40671 |   22 (1,5)  |    1D    | 2018-01-21 | PRD  | 0x3000 |  0x0   | Yes  |
+---+-------+-------------+----------+------------+------+--------+--------+------+

Press enter to exit

**Comment by platomav** [comment]
What's the problem? The -cont parameter is supposed to be used only at Intel microcode containers (.dat, .inc, .h) and not binaries.

**Comment by AndyLavr** [comment]
Aaa... Sorry...  And how to get .dat from .bin?

**Comment by AndyLavr** [comment]
Understood, thanks!
