### ISSUE TITLE
Error in linux kali distro Kernel v4.15 python3.6 lib error no attribute

### ISSUE THREAD

**Issue by mahmoud0x01** [platomav/MCExtractor#15]
the program is returned with the following **error**
`Error: MCE just crashed, please report the following:

Traceback (most recent call last):
  File "MCE.py", line 828, in <module>
    mce_hdr()
  File "MCE.py", line 787, in mce_hdr
    hdr_pt,hdr_pt_empty = mc_table([], False, 1)
  File "MCE.py", line 731, in mc_table
    if not param.cli_redirect : pt.set_style(prettytable.BOX_CHARS)
AttributeError: module 'prettytable' has no attribute 'BOX_CHARS'`

**Comment by platomav** [comment]
Answer is at issue #11 or #14
