### ISSUE TITLE
can I use mcextractor to find newest microcode blobs for my laptop

### ISSUE THREAD

**Issue by todin** [platomav/MCExtractor#16]
Hallo Plato

I've recently updated my lenovot x220 laptop to use coreboot. After that vendor released bios update (march 20). Bios update file is 8duj29us.exe and I would like to extract microcode blobs from it and then bundle them onto my coreboot.

There are two cases with it:
1. it find it very hard (to me at least) to extract microcode blob updates directly from .exe file. Option to install vendor bios onto my lenovo laptop, then reflash back to coreboot is troublesome way.
2. what if lenovo will abandon updating the bios for my laptop, while I still would like to use it.

My question is if I could use mcextractor to acquire new binary blobs for my x220 laptop.?

For the sake of completness, vendor BIOS for my laptop does contain following blobs:

flashregion_0_flashdescriptor.bin
flashregion_1_bios.bin
flashregion_2_intel_me.bin
flashregion_3_gbe.bin

all but flashregion_1_bios.bin were required by coreboot.

best regards,
Matt

**Comment by platomav** [comment]
Hi Matt,

MC Extractor is meant to be run on proper SPI/BIOS images and not custom OEM containers which should be manually unpacked first. Afterwards, MCE can show you whether your BIOS microcodes are updated or not based on its DB. As for the microcode binaries themselves, you can find the latest at the [CPU Microcode Repositories](https://github.com/platomav/CPUMicrocodes).

**Comment by todin** [comment]
thank You for the answer.

before transferring coreboot to my laptop I saved original rom from spi flash.
Can I use mc extractor on that to get newest microcode blobs?

**Comment by platomav** [comment]
You can but as I said, you can find the latest at the [CPU Microcode Repositories](https://github.com/platomav/CPUMicrocodes).

**Comment by platomav** [comment]
Python scripts are not compiled but "freezed" and you can run them after installing the code dependences via pip as seen at the Readme. The CPUID is 0x206A7 as can be seen from the "version information". It is obviously found at the DB since MCE detects its presence. Generally, this is not a MCE issue so any such questions should be addressed to Coreboot.

**Comment by todin** [comment]
thanks to Your directions I managed to run MCE.py. I've also managed to locate the latest bin file for my hardware:
cpu206A7_plat12_ver0000002D_2018-02-07_PRD_1BDB79EA.bin

Could You please tell me how can I extract blobs from it (me, bios, flashdescriptor, gbe)?
