### ISSUE TITLE
MCExtractor should add 1KB padding to files with odd file sizes

### ISSUE THREAD

**Issue by Squall-Leonhart** [platomav/MCExtractor#18]
Bios utilities expect the file to be power of 2, for instance, they can import a 4, 6, 8, 10, or 12KB microcode binary, but will fail on 3, 5, 7, 9, 11

for ease of injection, MCExtractor should add 1KB of zeroed data to the end of any microcode binary which is odd number.

For instance, the file cpu206C2_plat03_ver0000001F_2018-05-08_PRD_77DADA73.bin recently added is 11KB and fails to be inserted by any  version of MMTool, adding 1KB of dummy data to the end resolves this.

**Comment by platomav** [comment]
The microcodes are all proper. They have vendor sizes & checksums so MCE can verify the integrity of each extracted microcode precisely. Any AMI/MMTool specific errors or quirks are not relevant to MCE or the binary repository.

**Comment by platomav** [comment]
Any OEM can add whatever padding they want to accommodate their own SPI image, that obviously neither makes it right nor is the standard. You clearly have no notion of how microcodes are structured or distributed so please read [Intel's documentation](https://software.intel.com/en-us/articles/intel-sdm) for the main header and my own [Extra header](https://github.com/platomav/MCExtractor/wiki/Intel-Microcode-Extra-Undocumented-Header) analysis.
