### ISSUE TITLE
Msvcr100.dll shouldn't be there

### ISSUE THREAD

**Issue by mirh** [platomav/MCExtractor#2]
I'm not sure you are supposed/expected to redistribute VC runtime. 
Iirc it should be possible not-to-even need it, but even if I was wrong you could just link [this](https://www.microsoft.com/en-US/download/details.aspx?id=8328).

**Comment by platomav** [comment]
It should be ok to redistribute these as seen by MS [here](https://msdn.microsoft.com/en-us/library/ms235299(v=vs.100).aspx), [here](https://msdn.microsoft.com/en-us/library/8kche8ah(v=vs.100).aspx), [here](https://msdn.microsoft.com/en-us/library/dd293565(v=vs.100).aspx) and [here](https://www.visualstudio.com/license-terms/distributable-code-microsoft-visual-studio-2013-microsoft-visual-studio-2013-sdk-includes-u-2/). However, it doesn't matter anymore. Msvcr100.dll was only needed for Windows XP and when using Py2Exe to freeze the script. The next version of MCE will drop Windows XP support and PyInstaller will be used for freezing which does not require any VC runtime library dependencies which are not part of the stock Windows installation.

**Comment by mirh** [comment]
Oh god, it's msvcp100***d*** that you cannot redistribute. Sorry.
