### ISSUE TITLE
MC_Extractor_v1.24.2_r92 is Virus?

### ISSUE THREAD

**Issue by kuh3h3** [platomav/MCExtractor#23]
MCE,exe detected as trojan?
downloaded https://github.com/platomav/MCExtractor/releases/download/v1.24.2-r92/MC_Extractor_v1.24.2_r92.rar.
extract and run MCE,exe
Windows defender keeps telling me the MCE,exe is a virus, 
Trojan:Win32/Zpevdo.A

**Comment by platomav** [comment]
Obviously a false positive. Build/Freeze/Compile it yourself if you like.
