### ISSUE TITLE
Does the MCE.db can be put in a docker or kubernetes cloud ?

### ISSUE THREAD

**Issue by Azaretdodo** [platomav/MCExtractor#27]
Hello,

Does the MCE.db can be put in a docker or kubernetes cloud ?

Thank you in advance to agree or disagree,

If you know how to put the MCE.db file in docker or kubernetes I will like your knowing,

Regards.

Azaretdodo.

**Comment by platomav** [comment]
As long as the current [MCE license](https://github.com/platomav/MCExtractor/blob/master/LICENSE) ([BSD+Patent](https://opensource.org/licenses/BSDplusPatent)) is upheld and credit is given where it's due, there shouldn't be any problem with using these containers.
