### ISSUE TITLE
failed after install prettytables

### ISSUE THREAD

**Issue by Azaretdodo** [platomav/MCExtractor#28]
Hello I have install prettytables but now your python script crash :

`/opt/MCExtractor# python3 MCE.py
Traceback (most recent call last):
  File "/opt/MCExtractor/MCE.py", line 25, in <module>
    import prettytable
ModuleNotFoundError: No module named 'prettytable'
root@DESKTOP-HVPNCSO:/opt/MCExtractor# pip3 install prettytable
Collecting prettytable
  Downloading https://files.pythonhosted.org/packages/e0/a1/36203205f77ccf98f3c6cf17cf068c972e6458d7e58509ca66da949ca347/prettytable-0.7.2.tar.gz
Installing collected packages: prettytable
  Running setup.py install for prettytable ... done
Successfully installed prettytable-0.7.2
root@DESKTOP-HVPNCSO:/opt/MCExtractor# python3 MCE.py

Error: MC Extractor crashed, please report the following:

Traceback (most recent call last):
  File "/opt/MCExtractor/MCE.py", line 960, in <module>
    mce_hdr()
  File "/opt/MCExtractor/MCE.py", line 921, in mce_hdr
    hdr_pt,hdr_pt_empty = mc_table([], False, 1)
  File "/opt/MCExtractor/MCE.py", line 863, in mc_table
    pt.set_style(prettytable.UNICODE_LINES)
AttributeError: module 'prettytable' has no attribute 'UNICODE_LINES'

Press enter to exit`

Thank you in advance to help me runnig correctly your python scrypt :)

Regards.

Azaretdodo.

**Comment by Azaretdodo** [comment]
prettytable can be installed by python2 but now I have another error :

`/opt/MCExtractor# python MCE.py
Traceback (most recent call last):
  File "MCE.py", line 25, in <module>
    import prettytable
ImportError: No module named prettytable
root@DESKTOP-HVPNCSO:/opt/MCExtractor# pip install prettytable
Collecting prettytable
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/ef/30/4b0746848746ed5941f052479e7c23d2b56d174b82f4fd34a25e389831f5/prettytable-0.7.2.tar.bz2
Building wheels for collected packages: prettytable
  Running setup.py bdist_wheel for prettytable ... done
  Stored in directory: /root/.cache/pip/wheels/80/34/1c/3967380d9676d162cb59513bd9dc862d0584e045a162095606
Successfully built prettytable
Installing collected packages: prettytable
Successfully installed prettytable-0.7.2
root@DESKTOP-HVPNCSO:/opt/MCExtractor# python MCE.py
Traceback (most recent call last):
  File "MCE.py", line 26, in <module>
    from urllib import request
ImportError: cannot import name request
root@DESKTOP-HVPNCSO:/opt/MCExtractor# pip install request
Collecting request
  Downloading https://files.pythonhosted.org/packages/f1/27/7cbde262d854aedf217061a97020d66a63163c5c04e0ec02ff98c5d8f44e/request-2019.4.13.tar.gz
Collecting get (from request)
  Downloading https://files.pythonhosted.org/packages/3f/ef/bb46f77f7220ac1b7edba0c76d810c89fddb24ddd8c08f337b9b4a618db7/get-2019.4.13.tar.gz
Collecting post (from request)
  Downloading https://files.pythonhosted.org/packages/0f/05/bd79da5849ea6a92485ed7029ef97b1b75e55c26bc0ed3a7ec769af666f3/post-2019.4.13.tar.gz
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from request)
Collecting query_string (from get->request)
  Downloading https://files.pythonhosted.org/packages/12/3c/412a45daf5bea9b1d06d7de41787ec4168001dfa418db7ec8723356b119f/query-string-2019.4.13.tar.gz
Collecting public (from query_string->get->request)
  Downloading https://files.pythonhosted.org/packages/54/4d/b40004cc6c07665e48af22cfe1e631f219bf4282e15fa76a5b6364f6885c/public-2019.4.13.tar.gz
Building wheels for collected packages: request, get, post, query-string, public
  Running setup.py bdist_wheel for request ... done
  Stored in directory: /root/.cache/pip/wheels/30/84/5f/484cfba678967ef58c16fce6890925d5c7172622f20111fbfd
  Running setup.py bdist_wheel for get ... done
  Stored in directory: /root/.cache/pip/wheels/c1/e3/c1/d02c8c58538853e4c9b78cadb74f6d5c5c370b48a69a7271aa
  Running setup.py bdist_wheel for post ... done
  Stored in directory: /root/.cache/pip/wheels/c3/c3/24/b5c132b537ab380c02d69e6bd4dec1f5db56b5fe19030473d7
  Running setup.py bdist_wheel for query-string ... done
  Stored in directory: /root/.cache/pip/wheels/d6/a4/78/01b20a9dc224dcc009fab669f7f27b943b8889c5150bd68d8a
  Running setup.py bdist_wheel for public ... done
  Stored in directory: /root/.cache/pip/wheels/23/7c/6e/f5b4e09d6596c8b8802b347e48f149031e2363368048f1347a
Successfully built request get post query-string public
Installing collected packages: public, query-string, get, post, request
Successfully installed get-2019.4.13 post-2019.4.13 public-2019.4.13 query-string-2019.4.13 request-2019.4.13
root@DESKTOP-HVPNCSO:/opt/MCExtractor# python MCE.py
Traceback (most recent call last):
  File "MCE.py", line 26, in <module>
    from urllib import request
ImportError: cannot import name request`

Thank you in advance to help me run correctly your script in python by python2 or python 3 dev lang,

Regards.


Azaretdodo.

**Comment by platomav** [comment]
Follow the instructions in the README:

https://github.com/platomav/MCExtractor#c1-compatibility
https://github.com/platomav/MCExtractor#c2-code-prerequisites
