### ISSUE TITLE
Does MCExtractor python file install security update by ItSelf without doing ?

### ISSUE THREAD

**Issue by Azaretdodo** [platomav/MCExtractor#29]
Hello,

Does MCExtractor python file install security update by ItSelf without doing of user as myself ?

I have to CPUMicrocodes and Intel-Linux-Processor-Microcode-Data-Files github install at the same root...

Thabk you in advance for your sooner reply,

Regards.

Azaretdodo.

**Comment by platomav** [comment]
No, you can read its capabilities at the [README](https://github.com/platomav/MCExtractor#a-about-mc-extractor).

**Comment by Azaretdodo** [comment]
I am loosen with all says on the github...

I think I will go to the discussion topic because I don't know how to uses the programs...

I hope I will know how to uses the programs,

Regards.


Azaretdodo.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by Azaretdodo** [comment]
Hello I went to find the MCE executable command line following :


  *   -? : Displays help & usage screen
  *   -skip : Skips welcome & options screen
  *   -exit : Skips Press enter to exit prompt
  *   -mass : Scans all files of a given directory
  *   -info : Displays microcode header(s)
  *   -add : Adds new input microcode to DB
  *   -dbname : Renames input file based on DB name
  *   -search : Searches for microcodes based on CPUID
  *   -updchk : Checks for MC Extractor & DB updates
  *   -last : Shows "Last" status based on user input
  *   -repo : Builds microcode repositories from input
  *   -blob : Builds a Microcode Blob (MCB) from input

What command line I must use if a bin microcode is in the same root than the MCE executable for install the update?

What is the way for a Windows microcode update?

What is the way for a Linux microcode update?

If I have understood I must use blob and repo command line?

Have a nice day from France it is the holiday!

Thank you in advance to answer my questions I have don't disscuss on the discussion topic I firstly tried to know with us :)

Regards.


Azaretdodo.

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by Azaretdodo** [comment]
If it extract the microcode does It is able to install the microcode?

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________
