### ISSUE TITLE
Source of newer Intel microcodes

### ISSUE THREAD

**Issue by SmallJoker** [platomav/MCExtractor#31]
I would like to know the origin of newer Intel microcodes, especially those:

```
cpu1067A_plat44_ver00000A0E_2015-07-29_PRD_A3107D75.bin
cpu1067A_platB1_ver00000A0E_2015-07-29_PRD_59BF808E.bin
cpu10676_plat04_ver00000612_2015-08-02_PRD_AEAA6CC1.bin
cpu10676_plat40_ver00000612_2015-08-02_PRD_B6F50E9C.bin
cpu10676_plat91_ver00000612_2015-08-02_PRD_1750A2A6.bin
```

because they are newer than [Intel's official microcodes](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files). Corresponding entries from that repository:

```
║  79 │ 1067A │      11 (0,4)      │   A0B    │ 2010-09-28 │ PRD  │  0x2000 │ 0x36000  │  No  ║
║  80 │ 1067A │      44 (2,6)      │   A0B    │ 2010-09-28 │ PRD  │  0x2000 │ 0x38000  │  No  ║
║  81 │ 1067A │      A0 (5,7)      │   A0B    │ 2010-09-28 │ PRD  │  0x2000 │ 0x3A000  │  No  ║
║  73 │ 10676 │       01 (0)       │   60F    │ 2010-09-29 │ PRD  │  0x1000 │ 0x30000  │  No  ║
║  74 │ 10676 │       04 (2)       │   60F    │ 2010-09-29 │ PRD  │  0x1000 │ 0x31000  │  No  ║
║  75 │ 10676 │       10 (4)       │   60F    │ 2010-09-29 │ PRD  │  0x1000 │ 0x32000  │  No  ║
║  76 │ 10676 │       40 (6)       │   60F    │ 2010-09-29 │ PRD  │  0x1000 │ 0x33000  │  No  ║
║  77 │ 10676 │       80 (7)       │   60F    │ 2010-09-29 │ PRD  │  0x1000 │ 0x34000  │  No  ║
```

Is there any other official microcode repository, or could it be that Intel's is outdated?

**Comment by platomav** [comment]
Read the Disclaimer at the [CPUMicrocodes](https://github.com/platomav/CPUMicrocodes) repository to understand where microcodes are generally found. No exact logs are kept. All microcodes come from Intel and can be accepted by the microcode Loader only if they are official/proper. You should ask Intel if their repo is outdated or not but it looks that way.

**Comment by MarvinOl** [comment]
I was interested in this too as I have an old machine with 10676 CPU. It took some time but here's the gist.

In 2015 DefCon there was a presentation about Memory Sinkhole flaw in pre-sandy beach series of CPUs:
https://www.youtube.com/watch?v=lR0nh-TdpVg

Intel then released microcode updates for the affected CPUs but it was not widely published like the later Spectre etc updates. For example the 10676 and 1067A series Xeon CPU only specify errata until 2011:
https://www.intel.com/content/dam/www/public/us/en/documents/specification-updates/xeon-5400-spec-update.pdf

But the 2015 microcodes did make it around to system suppliers. For example this update from HP:
http://ftp.hp.com/pub/softpaq/sp73501-74000/sp73582.exe

It's dated EFFECTIVE DATE:  11/27/2015
In history.txt it contains:
Version 1.35 - Provides mitigation to the “Memory Sinkhole” issue affecting certain Intel processors based on older Intel micro-architectures.
               
And if you run the bios update thru mcextractor you will find that it contains:
║ 10 │ 10676 │  91 (0,4,7)  │   612    │ 2015-08-02 │ PRD  │ 0x1000 │ 0x2A9040 │ Yes  ║
║ 11 │ 10677 │    10 (4)    │   70D    │ 2015-08-02 │ PRD  │ 0x1000 │ 0x2AA040 │ Yes  ║
║ 13 │ 1067A │ B1 (0,4,5,7) │   A0E    │ 2015-07-29 │ PRD  │ 0x2000 │ 0x2AC040 │ Yes  ║

It is strange how this information is not really available anywhere and it was not just a 5 minute google search to figure it out.

**Comment by hmh** [comment]
> It is strange how this information is not really available anywhere and it was not just a 5 minute google search to figure it out.

It *is* available most of the time, *under NDA*, so it is no wonder it is not *generally* available.  As far as I know, you need to be on Intel's motherboard/chipset-level developer programs to be able to sign that NDA and maybe have access to that kind of information.

Nobody around here has signed that NDA, or we wouldn't even come close to working with microcode updates [in public] in the first place: since we *don't* have access to that information, we are not at risk of violating that NDA.

**Comment by MarvinOl** [comment]
I was trying to emphasize that at the moment there are microcode advisories and tables with microcode versions fixing specific vulnerabilities published by Intel. No NDA required, public information. But the 2015 Memory Sinkhole vulnerability does not even have a real wikipedia entry.
