### ISSUE TITLE
crash: "No module named prettytable"

### ISSUE THREAD

**Issue by Matthew-Bradley** [platomav/MCExtractor#34]
Hi,

I'm running the latest version of MCE on Ubuntu server 20.04 with python3.

When trying to launch the program, it crashes with the following error:
Traceback (most recent call last):
  File "MCE.py", line 25, in <module>
    import prettytable
ModuleNotFoundError: No Module Named 'Prettytable'

-Matt

**Comment by platomav** [comment]
https://github.com/platomav/MCExtractor/blob/master/README.md
