### ISSUE TITLE
-search option: Version explanation

### ISSUE THREAD

**Issue by Road-Drum** [platomav/MCExtractor#35]
Hi, I am currently digging BIOS files of my new potential motherboard, specifically AMD B550 chipset that is rumored to have zen/zen+ support depending on OEM. Using the downloaded BIOS of Phantom Gaming B550 ITX, I performed a search with CPUID `0800F11` which is the ID of my soon-to-be-transferred CPU (Ryzen 3 1200). 

the search succeed, displaying entries of `0800F11` as shown below

![image](https://user-images.githubusercontent.com/14361864/88135751-6097d280-cc1a-11ea-9c91-0475f11969e8.png)

while I could understand the date and size, I'm unsure what version means. Exact cpu model? cpu model string? 

why I'm choosing this board for my zen cpu is future proofing, of course and Asrock seems to have it in initial/factory bios

**Comment by platomav** [comment]
I'm not sure I understand. This is not a MCE issue. If you need help understanding the important values of microcodes, check the README of [Intel, AMD, VIA & Freescale CPU Microcode Repositories](https://github.com/platomav/CPUMicrocodes). If you need to ask other questions on compatibility etc then I suggest you go to forums such as the [Microcode section of Win-Raid](https://www.win-raid.com/f47-CPU-Microcodes.html) or similar. Also, you've probably misunderstood what -search does. It looks for microcode entries in the MCE DB, not the input BIOS image. Check without parameters to see the BIOS included microcodes.
