### ISSUE TITLE
View the whole MCE.db in human-readable text format?

### ISSUE THREAD

**Issue by mikebdp2** [platomav/MCExtractor#4]
I would like to check what's the latest microcode version for AMD CPU with ID = 610F31 , but your software doesn't have any option to print this information or at least print all known microcodes for AMD CPU's - so that I could manually look through for microcode info that belongs to CPU ID of my interest...

**Comment by platomav** [comment]
Hello,

You can use parameter -search to do what you want. From what I can tell though, there are no 00610F31 microcodes, only 00610F00 and 00610F01. However, AMD tends to change the CPUID of a processor while leaving the corresponding microcode to its original/intended value. Check your OEM's BIOS but I suspect that you are actually looking for F00 or F01 micocodes, not F31.
