### ISSUE TITLE
Update check  bug

### ISSUE THREAD

**Issue by LSSoniX** [platomav/MCExtractor#41]
Hello Plato.

![mce_bug](https://user-images.githubusercontent.com/20858707/106394816-a75b5600-640f-11eb-8713-2179d87e417d.JPG)

**Comment by platomav** [comment]
Fixed at 2e40e49. Thank you LSSoniX! :)

**Comment by LSSoniX** [comment]
V1.52.6 - Ok.
Thank you! :)
