### ISSUE TITLE
I can't install colorama... no command line pip works on my system window

### ISSUE THREAD

**Issue by Azaretdodo** [platomav/MCExtractor#44]
![image](https://user-images.githubusercontent.com/30596513/140619300-15ce82c9-6a44-4319-b674-9beee1e80542.png)

Hello,

Thank you in advance to help myself running fully your program,

I think the microcode is the following : 

![image](https://user-images.githubusercontent.com/30596513/140619321-b06d005f-1306-4c22-9b9d-7e2f0574d5df.png)

the inscpectre program say it is the followinf uid : 

![image](https://user-images.githubusercontent.com/30596513/140619334-0f48b4ae-57f9-49fb-a810-7c2927d287e1.png)

if you are agree thank you in advance to help myself launch the microcode,

Regards.

Azaretdodo.

**Comment by platomav** [comment]
Please look online on how to properly use a command prompt or PowerShell instance. Also, how to use pip. This is not an issue of MCE, so I'll go ahead and close it.
