### ISSUE TITLE
api-ms-win-core-path-l1-1-0.dll Missing (Win7)

### ISSUE THREAD

**Issue by direstraits96** [platomav/MCExtractor#48]
I'm getting this error while opening MCE.exe

Error loading Python DLL 'C:\Users\MyUserName\AppData\Local\Temp\_MEI60322\python39.dll'.

MyExe Version: v1.72.0
DB Version: DB r217

I'm guessing it's because python dropped support for Windows 7, but what can i do? I may need to build from source :(

**Comment by platomav** [comment]
Probably, Windows 7 support has been dropped at Python. I cannot suggest something more.
