### ISSUE TITLE
Show socket information

### ISSUE THREAD

**Issue by Piker-Alpha** [platomav/MCExtractor#5]
Can you add the (now missing) socket information? 

Note that 'Platform' is a bit mask for the supported sockets.

**Comment by platomav** [comment]
I am aware. Parameter -info shows the actual supported sockets/platforms.

**Comment by Piker-Alpha** [comment]
How does that work? I mean look at this code snippet:
```
		("Unknown5",      			  uint32_t),    # 44 dwords from Extra with encrypted padding or UpdateSize or Platform or Empty
		("SVN",     				  uint32_t),    # 48 Security Version Number
		("Unknown6",                  uint32_t),    # 4C 00000000 (always, reserved probably)
		("Unknown7",                  uint32_t),    # 50 00000000 (always, reserved probably)
		("Unknown8",                  uint32_t),    # 54 00000000 (always, reserved probably)
		("Unknown9",                  uint32_t),    # 58 00000000 (always, reserved probably)
		("Unknown10",                 uint32_t),    # 5C 00000000 (always, reserved probably)
```
That are the (supported) platform selectors. At least for Intel microcode.

**Comment by platomav** [comment]
You are confusing Platform and CPUID. Read the wiki page to learn what these fields mean.

https://github.com/platomav/MCExtractor/wiki/Intel-Microcode-Extra-Undocumented-Header

**Comment by Piker-Alpha** [comment]
Sorry? How? Listen. You may not understand me (it) but I have verified my findings in 30 by Intel provided microcode files. Your structure is not complete and incorrect.

**Comment by platomav** [comment]
There are a maximum of three Intel headers: Main, Extra and Extended. The work I've done at the wiki link above is indeed partially based on Ben's work and has to do exclusively with the undocumented Extra (as I call it) header. As far as I tell, you are talking about the Extended header which has nothing to do with Extra. If you look at the Extended header structure, you'll see that it is correct and not "staticly" used at the code itself. The info found at the Extended header is meant to be automatically copied to the Main header before the microcode is loaded, based on the ProcessorSignature that the system is currently using. For example, the Checksum found at the Extended entries is valid for the new Main header + patch data.
