### ISSUE TITLE
AMD cpu00A00F82 r220 microcode is older than being in r216!

### ISSUE THREAD

**Issue by karakarga70** [platomav/MCExtractor#50]
cpu00A00F82_ver0A008204_2021-10-15_A094A203.bin newer in r216
cpu00A00F82_ver0A008203_2021-05-11_27C2AC86.bin older in r220

**Comment by platomav** [comment]
The MCE DB includes everything, not the latest. It's a DB, after all. Not an issue.

**Comment by karakarga70** [comment]
As far as I know, the bigger the number, the newer the database. If this is not an issue, issue is you are an absent minded person at the time, preparing DB r220. I am warning you and you are not saying thanks for warning. Don't be so self confident, if in case making mistakes, admit it!

**Comment by karakarga70** [comment]
By the way, there is no any other place for me to contact you, are there. I know this way of selfish ones all at being "https://www.win-raid.com". The old aged near blind German, exactly opposite mooded Fernando, very similar Russian, SoniX like you. Be aware, you all do not deserve respect, you all are bad mooded pirates....
