### ISSUE TITLE
I can't compile MCE

### ISSUE THREAD

**Issue by Azaretdodo** [platomav/MCExtractor#53]
hello,

I can't compile MCE : 

```
python3 --noupx --onefile MCE.py
unknown option --noupx
usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

```

thanks you in advance to help myself pass this error,

Regards.

Azaretdodo.

**Comment by platomav** [comment]
The command run does not make sense. It's "pyinstaller", not "python3". Please follow the instructions carefully.

**Comment by Azaretdodo** [comment]
I will try with an installing of python,

I hope this is that,

Or I will search pyinstaller on Google,

Have a nice evening from the France,

Regards.


Dorian Rosse.
________________________________

**Comment by Azaretdodo** [comment]
Oh it is nice Google when it answer the problems :

https://pypi.org/project/pyinstaller/#:~:text=Project%20description-,PyInstaller%20bundles%20a%20Python%20application%20and%20all%20its%20dependencies%20into,Python%20interpreter%20or%20any%20modules.

Have a nice evening,

Regards.


Dorian Rosse.
________________________________
