### ISSUE TITLE
enum34 keep asked as uninstall

### ISSUE THREAD

**Issue by Azaretdodo** [platomav/MCExtractor#54]
hello,

I fall on error following : 

```
C:\MCExtractor-master>pyinstaller --noupx --onefile MCE.py
The 'enum34' package is an obsolete backport of a standard library package and is incompatible with PyInstaller. Please `pip uninstall enum34` then try again.

C:\MCExtractor-master>pip uninstall enum34
WARNING: Skipping enum34 as it is not installed.
```

as  you see i can't install pyinstaller,

thank you in advance to bring your help,

(i have success to import pyinstaller by pip3 this time but i hope for mean  about security use it),

Regards.

Azaretdodo.

**Comment by platomav** [comment]
Hi,

I'm not seeing any issue on my end, so it's something related to your system (Python version, pyinstaller version etc). Freezing MCE is not required, you can use the script directly after installing python 3.7+ and all "Code Prerequisites", as stated at the README. For potential Pyinstaller issues, you can open tickets at their own repository [here](https://github.com/pyinstaller/pyinstaller).
