### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by drSeehas** [platomav/MCExtractor#55]
At the Command Prompt typing MCE.exe the following window opens:
<img width="355" alt="MCE_Error" src="https://user-images.githubusercontent.com/106391705/170719087-d94cdda9-82dd-4639-b2da-8f7ba3fca366.png">
After clicking on "OK" the following appears in the Command Prompt window:
Error loading Python DLL 'C:\Users\Gerd\AppData\Local\Temp\_MEI142842\python39.dll'.
LoadLibrary: The specified module could not be found.
Where do I get this python39.dll file?

**Comment by platomav** [comment]
Make sure your OS is supported by Python 3.9 (Windows 8+).

**Comment by drSeehas** [comment]
At least v1.70 worked still on Windows 7.

**Comment by platomav** [comment]
The minimum required version of Python for MCE is 3.7, currently. You can try using the script directly after installing Python 3.7 and any needed dependencies, as detailed at the README. Windows 7 is deprecated, nothing more I can suggest.
