### ISSUE TITLE
Add old RC4 style ucode and ELF XuCode decrypter as per chip-red-pill/MicrocodeDecryptor

### ISSUE THREAD

**Issue by ValZapod** [platomav/MCExtractor#56]
[chip-red-pill/MicrocodeDecryptor](https://github.com/chip-red-pill/MicrocodeDecryptor)

https://github.com/platomav/CPUMicrocodes/blob/bbf616a1c97ab81800a9dc67360b1fd600050a45/Intel/cpu506C9_plat03_ver00000040_2020-02-27_PRD_2FC3D618.bin

**Comment by platomav** [comment]
This is out of scope for this project. If someone wants that, they can use the tools from the other repo.
