### ISSUE TITLE
Problem starting MCExtractor

### ISSUE THREAD

**Issue by MC-Half** [platomav/MCExtractor#57]
Hi,
I have downloaded MC Extractor and python310.dll but it will not start.
python310.dll is in the same folder and also C:\Windows\SysWOW64\ and C:\Windows\System32\
 I include screen grabs.
![MCE exe - System Error](https://user-images.githubusercontent.com/113150726/189248036-0b930c47-3b49-4d52-bdf1-dab83de23133.jpg)
![Python310 dll - problem](https://user-images.githubusercontent.com/113150726/189248055-d8e41c85-c468-4a7c-8880-99a71c9bebc0.jpg)

**Comment by platomav** [comment]
https://pythondev.readthedocs.io/platforms.html#windows
