### ISSUE TITLE
Some of latest Intel microcodes not detected

### ISSUE THREAD

**Issue by ichee** [platomav/MCExtractor#59]
Intel microcode version 3303 for CPUID's 50656 and 50657 are not seen as a microcode by MCE.

The latest version of UEFITool NE can see them properly.

Listed microcode above found at: https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files

UEFITool NE found at: https://github.com/LongSoft/UEFITool

MCE microcode file:
![mce_cap](https://user-images.githubusercontent.com/22252639/220521801-945aef45-9a5c-4f7b-ba4c-1f24a3254e96.png)

MCE modded BIOS:
![mce_mod_cap](https://user-images.githubusercontent.com/22252639/220523392-9af78ffb-496a-4368-b9dc-884ec6fbdbfb.png)

UEFITool NE:
![uefitool_cap](https://user-images.githubusercontent.com/22252639/220521858-15367e37-4e5c-44ca-9598-53b3312bab5f.png)

For a comparison, the previous microcode 3302 for CPUID's 50656 and 50657 are detected properly.

MCE previous modded BIOS:
![mce_mod_prev_cap](https://user-images.githubusercontent.com/22252639/220525108-b38e4cd7-8f31-4096-a0f3-2e8a8d4c86d9.png)

**Comment by platomav** [comment]
It appears that after 28 (!) years, Intel decided to start using the "Reserved" fields at the end of the microcode header from 0x24-0x30. Thus, I have removed the "Reserved" bytes from the end of the Intel regex pattern and any such updates can be properly detected now.

The earliest such microcode I was able to find in a quick scan is from August 2022, so I assume this changes happened in the middle of last year. It's probable that some microcodes may have been lost in the meantime, but hopefully they can be detected and added at some point in the future. For now, I was able to find and add 25 missing microcodes.

The latest commit [7e58a44](https://github.com/platomav/MCExtractor/commit/7e58a44fd3637e0627f01e13ef63c6d92a6d922a) should have fixed the problem, and I'm thus going to close this issue as completed.

Huge thanks for the report @ichee and for using MCE.

**Comment by andyhhp** [comment]
@platomav Yeah, some politics started with https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a77a94f86273ce42a39cb479217dd8d68acfe0ff removing the ability to do late microcode loading in Linux (5.19)

https://lore.kernel.org/lkml/20230130213955.6046-7-ashok.raj@intel.com/ has a few details about the new scheme.

**Comment by platomav** [comment]
This is fascinating, thank you for the resources @andyhhp. Reading that list but also the commits from ["arch/x86/include/asm/microcode_intel.h"](https://github.com/torvalds/linux/commits/master/arch/x86/include/asm/microcode_intel.h), it appears Intel as been busy lately with the microcode format. Here are the changes I read about:

1. Header "Version" is actually "Type" with 1 meaning "Microcode" and 2 "In-Field Scan" (IFS)
2. Reserved 1/3 (i.e. 0x24-0x28) is now [IFS Metadata Size](https://github.com/torvalds/linux/commit/aa63e0fda85edf9a8431fc31a2b2d4f3f40592f9) for the Header Type 2 structures.
3. Reserved 2/3 (i.e. 28-0x2C) is now "Minimum Required Version" for avoiding OS Kernel Late Loading incompatibilities. 

I have created a new ticket #60 to track these new additions to MCE.
