### ISSUE TITLE
Add support for new Intel Microcode header fields + In-Field Scan (IFS) type

### ISSUE THREAD

**Issue by platomav** [platomav/MCExtractor#60]
Based on the feedback by @andyhhp at https://github.com/platomav/MCExtractor/issues/59#issuecomment-1462954015 and the commits from https://github.com/torvalds/linux/commits/master/arch/x86/include/asm/microcode_intel.h, it appears Intel has been busy lately with the microcode format. Here are the changes that need to be implemented in MCE:

1. Header Version (i.e. 0x00-0x04) is actually [Header Type](https://github.com/torvalds/linux/commit/aa63e0fda85edf9a8431fc31a2b2d4f3f40592f9) with 1 meaning "Microcode" and 2 "In-Field Scan" (IFS).
2. Reserved 1/3 (i.e. 0x24-0x28) is now [IFS Metadata Size](https://github.com/torvalds/linux/commit/28377e56ed22ecce60260eb8afdf0c9837b3505f) for the Header Type 2 structures.
3. Reserved 2/3 (i.e. 0x28-0x2C) is now [Minimum Required Version](https://lore.kernel.org/lkml/20230130213955.6046-7-ashok.raj@intel.com/) for avoiding OS Kernel Late Loading incompatibilities.

**Comment by platomav** [comment]
Description of the new IFS Metadata data block within the microcode blob (i.e. after data but before extended signatures):

https://lore.kernel.org/lkml/20221021203413.1220137-9-jithu.joseph@intel.com/

**Comment by NikolajSchlej** [comment]
Adding myself to CC so I can port the required changes to UEFITool when they land.

**Comment by platomav** [comment]
Added IFS detection at https://github.com/platomav/MCExtractor/commit/32de67472e3092505ce290f573cb587c06d48344
