### ISSUE TITLE
Not an issue but problem!

### ISSUE THREAD

**Issue by karakarga07** [platomav/MCExtractor#62]
Hello, are there anywhere that I can download mce.exe for r272 and future releases? Can you please give me a link?

**Comment by platomav** [comment]
https://github.com/platomav/MCExtractor#c-download-mc-extractor

**Comment by karakarga07** [comment]
At the link there is no mce.exe file. I am looking for mce.exe about 8 MB in size. I have currently 8685 kb for r271)
