### ISSUE TITLE
Not an issue but problem 2

### ISSUE THREAD

**Issue by karakarga07** [platomav/MCExtractor#63]
At your given link: https://github.com/platomav/MCExtractor#c-download-mc-extractor

There is no mce.exe file. I am looking for mce.exe about 8 MB in size. I have currently 8685 kb for r271)

When I click the mce.exe file, it says: "MC Extractor v1.90.2 r271" inside the reactangle at the top. I am looking for r272 and for future ones, is there a link for it!

**Comment by platomav** [comment]
Only the Python script is provided, not in frozen state.
