### ISSUE TITLE
Missing Changelog.txt entry for r272

### ISSUE THREAD

**Issue by cmisare** [platomav/MCExtractor#66]
I believe the entry for `Intel cpu806C1_plat80_ver000000AC_2023-02-27_PRD_94911A3C` is missing in the Changelog.txt for r272.

https://github.com/platomav/MCExtractor/commit/5dd72f5308886144a73931df94a787dc2e18e3b5

https://github.com/platomav/CPUMicrocodes/commit/fbb9c744f61157534fb0e6a3cc89236760bd89e3

**Comment by platomav** [comment]
Thank you for the feedback. Yeah it could be, it can happen with such manual processes. It doesn't affect anything, though, so I'll go ahead and close this issue.
