### ISSUE TITLE
AMD AM4 Microcode isn't up-to-date

### ISSUE THREAD

**Issue by srialmaster** [platomav/MCExtractor#70]
When using the mce.py to update the BIOS microcode, it continues to think that cpu00800F12's latest is 0800126E, when the latest is 126F. It will continue to keep showing the last as "No" for this one.

<img width="388" alt="image" src="https://github.com/user-attachments/assets/067056ca-f98f-414f-a122-60014c2a6314">

**Comment by srialmaster** [comment]
cpu00800F12_ver0800126F_2023-12-19_259A67AF.bin is the latest in the CPUMicrocodes/AMD folder.

**Comment by platomav** [comment]
This project is not related to UBU. Please ask any such questions to the developer(s) of the latter.
