### ISSUE TITLE
UBU hidden switch removed

### ISSUE THREAD

**Issue by srialmaster** [platomav/MCExtractor#71]
Can you add the -ubu hidden switch back to the mce.py?

`	Line  112:         self.mce_ubu = False
	Line  130:         if '-ubu' in source : self.mce_ubu = True # Hidden
	Line  911:     if param.mce_ubu : return
	Line  976:     pt.left_padding_width = padd if not param.mce_ubu else 0
	Line  977:     pt.right_padding_width = padd if not param.mce_ubu else 0
	Line  988:     if param.mce_ubu : padd = 0
	Line 1027: if not param.mce_ubu : sys.excepthook = show_exception_and_exit
	Line 1099: if not param.mce_ubu :
	Line 1343:     if not param.mce_ubu :
	Line 1604:         if not param.mce_ubu and not os.path.exists(extr_dir_int) : os.makedirs(extr_dir_int)
	Line 1793:         if not param.mce_ubu and not os.path.exists(extr_dir_amd) : os.makedirs(extr_dir_amd)
	Line 1917:         if not param.mce_ubu and not os.path.exists(extr_dir_via) : os.makedirs(extr_dir_via)
	Line 2056:         if not param.mce_ubu and not os.path.exists(extr_dir_fsl) : os.makedirs(extr_dir_fsl)
	Line 2178: mce_exit(mc_nr if param.mce_ubu else 0)
`
I modified your latest mce.py to add all of these back and it works with the UBU tool again. BTW, SonicX is back and working on this project again.

**Comment by platomav** [comment]
No, MCE will not have any special code for UBU.
