### ISSUE TITLE
Compatibility with UBU Tool for newer Databases

### ISSUE THREAD

**Issue by Starfoxfs** [platomav/MCExtractor#72]
Hi,

i use the UBU Tool 1.79.17 for Bios Modding to add latest Microcodes.
(https://forums.overclockers.ru/viewtopic.php?f=1&t=479847&sid=7fb400a2385be9faf91257fc8ac78569&start=14020)

The newer MCE Databases wouldn´t run with this Command Line Tool correctly, because the MCE.py is different to the older MCE.py what was used with 1.79.17 UBU Tool.
It´s Version 2.71 with MCE.py 1.90.2

So i get Error Messages as "Not in Database" or Error -UBU File is missing.

Can you Fix this please, newer Microcodes where still available and this Tool is nice and easy to Update it.

Big Thanks

**Comment by platomav** [comment]
Hello,

There is no support for UBU utility within MCE, they are unrelated projects. There is nothing for MCE to "fix". If UBU wants to utilize MCE, it would need to be integrated on its side.
