### ISSUE TITLE
cpu406F1_platEF_ver0B000025_2017-11-18_PRD_F0B0963D .bin download ?

### ISSUE THREAD

**Issue by bios-x** [platomav/MCExtractor#8]
I've seen cpu406F1_platEF_ver0B000025_2017-11-18_PRD_F0B0963D listed in DB r48

Can you email/post this .bin file in Fernando's Win-RAID Forum for me to use

Thanks

**Comment by platomav** [comment]
@bios-x Please check the ReadMe file from the latest commit to find the CPU Microcode Repositories thread.
